### ISSUE TITLE
wasm-opt fails when using WASM_INTERFACE_TYPES=1

### ISSUE THREAD

**Issue by JesterOrNot** [rustwasm/wasm-pack#793]
## 🐛 Bug description
The webassembly breaks when I have wasm-opt on
![image](https://user-images.githubusercontent.com/50386709/74606839-4ff69580-5099-11ea-8356-3d68b4f51316.png)
I am able to get around the error when I add
```toml
[package.metadata.wasm-pack.profile.dev]
wasm-opt = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
```
But It should work even if I add the optimizations.
#### 🤔 Expected Behavior
It still compiles when I use the optimizations
#### 👟 Steps to reproduce
https://github.com/JesterOrNot/markdown_wasi/tree/bug
Run `make` and see the error
#### 🌍 Your environment
Open in the browser https://gitpod.io/#https://github.com/JesterOrNot/markdown_wasi/tree/bug
Include the relevant details of your environment. Gitpod Cloud IDE based on ubuntu docker
wasm-pack version: 0.9.1
rustc version: 1.4.1

**Comment by Pauan** [comment]
To clarify, does it work correctly if you don't use `WASM_INTERFACE_TYPES=1`?

**Comment by JesterOrNot** [comment]
No

**Comment by JesterOrNot** [comment]
The function I'm using is https://github.com/bytecodealliance/wasmtime-demos/blob/master/markdown/src/lib.rs

**Comment by JesterOrNot** [comment]
Try running the function with WASM_INTERFACE_TYPES=1 in the example repo

**Comment by Pauan** [comment]
If it's still erroring even when not using `WASM_INTERFACE_TYPES=1`, then this sounds similar to https://github.com/rustwasm/wasm-pack/issues/696

**Comment by JesterOrNot** [comment]
Just looked through it. But if that was the case it should be fixed right?

**Comment by ratnadeep007** [comment]
Same error here also. Trying to follow tutorial and got this error. 

Also tried adding:
```toml
[package.metadata.wasm-pack.profile.dev]
wasm-opt = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
```
Still it doesn't compile. Also tried adding `wasm-opt` from `npm` still failing. When not using `WASM_INTERFACE_TYPES=1` its still failing. Only way around is to add:

```toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

Hope this issue resolves soon.

**Comment by MattesWhite** [comment]
Has there been any progress on this issue in the meantime? I also face the error:

```
> WASM_INTERFACE_TYPES=1 wasm-pack build
...
[parse exception: Only 1 table definition allowed in MVP (at 0:448)]
```

And therefore can't run the `wasm` using wasmtime.

The suggested editing of `[package.metadata.wasm-pack.profile.release]` didn't worked for me.

---
```
> rustc --version
rustc 1.45.0 (5c1f21c3b 2020-07-13)
> wasm-pack --version
wasm-pack 0.9.1
> wasm-opt --version
wasm-opt version 91
> wasmtime --version
wasmtime 0.19.0
```

**Comment by jrheard** [comment]
I'm encountering the same issue that @ratnadeep007 describes when working through https://rustwasm.github.io/docs/book/game-of-life/implementing.html . The `wasm-opt = false` workaround resolves the issue, but it definitely feels like something's broken.

**Comment by PiepsC** [comment]
For me this could also be prevented by downgrading from the current 0.9.2 to 0.8.1 as described in #782.
`cargo install wasm-pack --version 0.8.1`

I ran into the same issue on x64 Arch and Windows.

**Comment by temasictfic** [comment]
In the game of life  example render function causing this error which returns String. If you use canvas api, no need for this function and fmt::Display implementation. After that wasm-opt worked as expected. (wasm-pack version 0.9.1)

**Comment by SeedyROM** [comment]
A good idea is to run `which wasm-opt` and see where it's installed, then check when it was installed. In my case I had an ancient `wasm-opt` version installed by some unknown tool. So I removed it and it was able to find the correct binary. [See here](https://github.com/trunk-rs/trunk/issues/904#issuecomment-2892870802)!
